title: "Portfolio - Yasmina AGHARMINE"
avatar: /23191A05-C7BC-40AD-9285-710677A87B0C.jpg
logo: /23191A05-C7BC-40AD-9285-710677A87B0C.jpg
description: "Porfolio Future Tchecnicienne/Administratrice Réseaux et Cybersécurité"
show_downloads: true
theme: jekyll-theme-dark-light
lang: fr
